version: '2.1'

services:
  workshop_webpack:
    image: workshop_webpack
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/src/app
    command: node --inspect index.js